name: Demo – Compose + Cloudflare Tunnel
on:
  workflow_dispatch: 
  push:
      branches: [ "master", "dev/ci_cd" ]
jobs:
  Deploy:
    runs-on: self-hosted
    timeout-minutes: 480 
    steps:
      - uses: actions/checkout@v4

      - name: Compose up
        run: docker compose --profile "" up --build -d

      - name: Install cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Start tunnel
        run: cloudflared tunnel --url http://localhost:5173 --no-autoupdate