name: Demo – Compose + Cloudflare Tunnel
on:
  workflow_dispatch: 
  push:
      branches: [ "master", "dev/ci_cd" ]
jobs:
  preview:
    runs-on: self-hosted           
    steps:
      - uses: actions/checkout@v4

      - name: Compose up
        run: docker compose --profile "" up --build -d

      - name: Install cloudflared
        uses: AnimMouse/setup-cloudflared@v2
        
      - name: Start tunnel
        run: cloudflared tunnel --url http://localhost:5173 --no-autoupdate

      - name: Start tunnel & capture URL
        id: tunnel
        shell: powershell
        run: |
          Start-Process -FilePath cloudflared `
                        -ArgumentList 'tunnel','--url','http://localhost:5173','--no-autoupdate' `
                        -RedirectStandardOutput tunnel.log `
                        -RedirectStandardError  tunnel.log `
                        -WindowStyle Hidden
          Start-Sleep -Seconds 8
          $urlLine = Select-String -Path tunnel.log -Pattern 'https://.*\.trycloudflare\.com' |
                    Select-Object -First 1
          $publicUrl = $urlLine.Matches.Value
          "PUBLIC_URL=$publicUrl" >> $env:GITHUB_OUTPUT

      - name: Publish demo URL
        run: |
          echo "### 🚀 Demo URL" >> $env:GITHUB_STEP_SUMMARY
          echo "${{ steps.tunnel.outputs.PUBLIC_URL }}" >> $env:GITHUB_STEP_SUMMARY
        shell: bash