name: Demo – Compose + Cloudflare Tunnel
on: 
  push:
      branches: [ "master", "dev/ci_cd" ]
jobs:
  preview:
    runs-on: self-hosted           
    steps:
      - uses: actions/checkout@v4

      - name: Compose up
        run: docker compose --profile "" up --build -d

      - name: Install cloudflared
        uses: AnimMouse/setup-cloudflared@v2
        
      - name: Start tunnel
        run: cloudflared tunnel --url http://localhost:5173 --no-autoupdate