name: Demo – Compose + Cloudflare Tunnel
on:
  workflow_dispatch:
  push:
      branches: [ "master", "dev/ci_cd" ]
jobs:
  preview:
    runs-on: self-hosted           
    steps:
      - uses: actions/checkout@v4

      - name: Compose up
        run: docker compose --profile "" up --build -d

      - name: Start Cloudflare tunnel
        id: tunnel
        uses: vmactions/cf-tunnel@v0
        with:
          protocol: http
          port: 5173


      - name: Output demo URL
        run: |
          echo "### Demo URL" >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.tunnel.outputs.server }}" >> "$GITHUB_STEP_SUMMARY"
          echo "Demo available at: ${{ steps.tunnel.outputs.server }}"