name: CI – Docker Compose Integration

on:
  push:
    branches: [ "master", "dev/ci_cd" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services with Docker Compose
        run: docker compose -f docker-compose.yml up --build -d

      - name: Wait for backend
        run: sleep 20

      - name: Check backend health
        run: curl --fail http://localhost:8000/api-docs || exit 1

      - name: Run integration tests
        run: docker compose exec -T backend npm run test
        working-directory: backend

      - name: Shut down containers
        run: docker compose -f docker-compose.yml down
