name: CI – frontend

on:
  push:
    branches: [ "master", "dev/ci_cd" ]
  pull_request: 
    branches: [ "master" ]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:             
      run:
        working-directory: frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22      
        cache: 'npm'

    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - run: npm test
